##############################
# Library B instance Config  #
##############################

# Apollo STOMP Broker Configuration
stompQueueName: 53730.book.orders

# Library B subscribes to the Computer category ONLY!
stompTopicName: "53730.book.computer"

# Name for library A
libraryName: library-b

# Apollo STOMP Broker URL and login
apolloUser: "admin"
apolloPassword: "password"
apolloHost: "54.215.133.131"
apolloPort: 61613

# HTTP-specific options.
server:
  type: simple
  applicationContextPath: /library
  adminContextPath: /admin
  connector:
    type: http
    port: 8002


