# Library A instance Config  #
##############################

# Apollo STOMP Broker Configuration
stompQueueName: 53730.book.orders

# Library A subscribes to all book categories If book.* doesn't work, try book.all
stompTopicName: "53730.book.*"



# Name for library A
libraryName: library-a

# Apollo STOMP Broker URL and login
apolloUser: "admin"
apolloPassword: "password"
apolloHost: "54.215.133.131"
apolloPort: 61613

# HTTP-specific options.
server:
#  applicationContextPath: /library/*
  # Root Path http://{host}:{port}/xxx
  applicationConnectors:
      - type: http
        port: 8003

#
#   adminConnectors:
#      - type: http
#        port: 9002


